### ISSUE TITLE
java

### ISSUE THREAD

**Issue by xudong-jason** [PacktPublishing/Mastering-Spark-for-Data-Science#4]
hi，this book has java code in spark?

**Comment by mrhalle** [comment]
No, but it doesn't need to (although there is plenty of Java): We have generally tried to implement code in the artifacts' native language; for example, where Accumulo is extended we would use Java since Accumulo is written in Java. For Spark we have primarily used Scala as this seamlessly integrates with Java (they both run in JVM), and we have implemented and extended the Hadoop stack (almost exclusively Java) a great deal. A fair bit of the Scala code is written in a more OO way, with some functional, and so we feel the leap between Java and OO Scala is relatively small; but we have also met the needs of the functional community. In the modern commercial world it is certainly necessary to command a knowledge of multiple languages, we feel the book well demonstrates the many and varied ways that different languages can interact and co-exist.
